### PR TITLE
improve domain check for authorization cookie.

### LINKED ISSUE #54: Remove same domain restriction
What is the reason for restricting Mercure Authentication to the same (Sub-)Domain?

Our Api runs at `api.mydomain.tld` and Mercure at `mercure.mydomain.tld` 

This check makes it impossible for us to get authorization working https://github.com/symfony/mercure/blob/main/src/Authorization.php#L97

Can it be removed or do have any security concerns?
If not i suggest removing this check or make it at least configurable

### PR DESCRIPTION
**Pull request by azjezz**
closes #54

### CODE REVIEW

**Comment by azjezz** [comment]
@dunglas this would allow setting cookies for foo.com.tn from bar.com.tn, but these are not really popular cases and having a map of all TLDs is an overkill, i suggest we keep it simple, and see if someone hits one of these cases :p

**Comment by norkunas** [comment]
Could this be merged? :)

**Comment by dunglas** [comment]
Could you rebase please @azjezz?

**Comment by azjezz** [comment]
rebased

**Comment by azjezz** [comment]
failure unrelated: https://github.com/symfony/mercure/pull/57#pullrequestreview-664040559

**Comment by dunglas** [comment]
Thanks @azjezz

**Pull request merged**
