### PR TITLE
Add method to delete cookie

### LINKED ISSUE #55: Add cookie deletion
I see there is added a new `Authorization` class which helps to create mercure cookies, but I think the deletion then should be also added :)

### PR DESCRIPTION
**Pull request by norkunas**
Closes #55

### CODE REVIEW

**Review by dunglas — APPROVED** [review]
Wow that was fast!

**Comment by dunglas** [comment]
Could you rebase please?

**Comment by norkunas** [comment]
> Could you rebase please?

Rebased :)

**Comment by dunglas** [comment]
Thanks @norkunas

**Pull request merged**
