### PR TITLE
Feat: Security: Allow subsribe and publish topics to be passed as null to token factory

### PR DESCRIPTION
**Pull request by silverbackdan**
I believe this addresses
Fix: https://github.com/symfony/mercure/issues/80
Fix: https://github.com/symfony/mercure/issues/92

### CODE REVIEW

**Comment by silverbackdan** [comment]
I've also added a constructor argument for the cookie samesite to address
https://github.com/symfony/mercure/issues/92

Very quick simple change here and if approved and merged I could update the mercure bundle as well to allow a configuration option.

**Review by chalasr — APPROVED** [review]
👍 for me, thanks for the PR!

**Comment by silverbackdan** [comment]
Sorry to pin @dunglas - I know you're probably very busy. This would be a great security fix for me so user's with the JWT key can be restricted from publishing.

**Review by dunglas — APPROVED** [review]

**Comment by dunglas** [comment]
Thank you!

**Comment by silverbackdan** [comment]
Thanks very much for merging, I can't seem to use the dev-main branch with the mercure bundle so just wondering if there is any expected timeline for a minor version release?

**Comment by dunglas** [comment]
released!

**Pull request merged**
